name: 'ntd - create tag'
description: 'ntd - create tag'
inputs:
  token:
    description: GitHub token
    required: true
  name: 
    description: tag name
    required: true
    default: 0.0.0
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: arrow-up-circle
  color: blue
